#!/usr/bin/env node
'use strict';

var program  = require('commander');




program
	.version('0.0.0');


program
	.on('*', function(name) {
		console.log('\''+name+'\' is not a known command. See \'rndr --help\':');
		program.outputHelp();
		process.exit(1);
	});


program
	.parse(process.argv);

if (program.args.length < 1 ) {
	console.log('No command specified. See \'rndr --help\':');
	program.outputHelp();
	process.exit(1);
}
